### ISSUE TITLE
Could not locate module 'data' 

### ISSUE THREAD

**Issue by tdminer** [extreme-bert/extreme-bert#2] opened 2022-12-07 00:46 UTC
File shard_data.py depends on module 'data' (from data import TextSharding), which was missing from the repository.
I think the file TextSharding.py was based on the file [https](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/LanguageModeling/BERT/data/TextSharding.py)
However, the file signature is different. shard_data.py has 12 positional arguments and the original file only has 6 positional arguments.

**Comment by research4pan** [comment] 2022-12-07 01:15
Hi, @tdminer thanks for the feedback! We've uploaded the missing module. You may check if the problem is fixed now. It was caused by a mistake when moving files to public repository. Thanks for informing us about that~🤗

**Closed as completed** 2022-12-08 15:16 UTC
